#!/usr/bin/env bash
# Write results/REPORT.md: every SWE-bench column in one place, one column per
# model and harness version, merging the directories a run was split across
# (shards, and night 1 + night 2 resumes). Columns are defined by directory
# globs here, so the report is reproducible from what is in results/.
set -euo pipefail
cd "$(dirname "$0")/.."

join() { { ls -d $1 2>/dev/null || true; } | tr '\n' ',' | sed 's/,$//'; }  # a glob with no match is an absent column, not an error
cols=()
add() { local label=$1 dirs; dirs=$(join "$2"); [[ -n "$dirs" ]] && cols+=(--col "$label=$dirs"); return 0; }

# held-out, pre-registered baselines (harness 0.3.1)
add "Codestral h0.3.1 held-out" "results/*codestral-latest-reindent-swe-heldout-s[0-9] results/*codestral-latest-reindent-swe-heldout-n2-s[0-9]"
add "qwen3.5-9B h0.3.1 held-out" "results/*qwen3.5-9b-32k-reindent-swe-heldout-nothink results/*qwen3.5-9b-32k-reindent-swe-heldout-n2-qwen"
add "Codestral h0.6.1 held-out" "results/*codestral-latest-reindent-swe-heldout-h061*"
# dev comparison
add "Codestral h0.3.0 dev" "results/*codestral-latest-reindent-swe-dev results/*codestral-latest-reindent-swe-dev-n2-h03"
add "Codestral h0.4.0 dev" "results/*codestral-latest-reindent-swe-dev-h04 results/*codestral-latest-reindent-swe-dev-h04-resume"
add "Codestral h0.5.0 dev" "results/*codestral-latest-reindent-swe-dev-h05"
add "Codestral h0.6.0 dev" "results/*codestral-latest-reindent-swe-dev-h06"
add "Codestral h0.6.1 dev" "results/*codestral-latest-reindent-swe-dev-n2-h061"
add "qwen3.5-9B h0.3.0 dev" "results/*qwen3.5-9b-32k-reindent-swe-dev-nothink"

{
  echo "# Brokkr results on SWE-bench Verified (Django 4.x)"
  echo
  echo "Generated by \`scripts/make-report.sh\` on $(date -u +%Y-%m-%dT%H:%MZ) from \`results/\`."
  echo "Verdicts are Brokkr's verification against SWE-bench's hidden tests, never the agent's claim."
  echo "Held-out tasks are the 82 valid tasks of \`results/swe/split.json\` 'test'; dev tasks may have"
  echo "shaped the harness. Plan and amendments: \`results/swe/plan.json\`. Narrative: \`NIGHTLOG.md\`."
  echo
  python3 scripts/report.py "${cols[@]}" --split results/swe/split.json --difficulty-json results/swe/difficulty.json

  # Paired comparisons on the tasks both runs scored (exact McNemar test).
  B=$(join "results/*codestral-latest-reindent-swe-heldout-s[0-9] results/*codestral-latest-reindent-swe-heldout-n2-s[0-9]")
  N=$(join "results/*codestral-latest-reindent-swe-heldout-h061*")
  Q=$(join "results/*qwen3.5-9b-32k-reindent-swe-heldout-nothink results/*qwen3.5-9b-32k-reindent-swe-heldout-n2-qwen")
  echo
  echo "## Paired comparisons (Django held-out)"
  if [[ -n "$B" && -n "$N" ]]; then echo; echo "### Codestral: harness 0.3.1 vs 0.6.1"; echo; python3 scripts/compare.py "h0.3.1=$B" "h0.6.1=$N"; fi
  if [[ -n "$B" && -n "$Q" ]]; then echo; echo "### Harness 0.3.1: Codestral vs qwen3.5-9B (local)"; echo; python3 scripts/compare.py "Codestral=$B" "qwen3.5-9B=$Q"; fi

  # SymPy: its own split and its own table, never pooled with Django.
  scols=()
  d=$(join "results/*codestral-latest-reindent-swe-sympy-dev-n2-h061"); [[ -n "$d" ]] && scols+=(--col "Codestral h0.6.1 dev=$d")
  d=$(join "results/*codestral-latest-reindent-swe-sympy-heldout-n2-h061*"); [[ -n "$d" ]] && scols+=(--col "Codestral h0.6.1 held-out=$d")
  if [[ ${#scols[@]} -gt 0 ]]; then
    echo
    echo "# SymPy (SWE-bench Verified, all versions)"
    echo
    echo "Split: \`results/swe/split-sympy.json\` (10 dev, 65 held-out). Pass rule: SWE-bench's own"
    echo "(\`required_only\`: every required test passes; exit code ignored). See NIGHTLOG, night 2."
    echo
    python3 scripts/report.py "${scols[@]}" --split results/swe/split-sympy.json --difficulty-json results/swe/difficulty.json
  fi

  # pydantic: recent fixes (merged on/after 2026-03-01), evaluation-only.
  pc=$(join "results/*pydantic-codestral-*")
  if [[ -n "$pc" ]]; then
    echo
    echo "# pydantic (fixes merged on/after 2026-03-01; not in SWE-bench)"
    echo
    echo "Tasks built from GitHub by \`scripts/gh/prepare.py\`; required tests derived as SWE-bench does."
    echo "All tasks held out (\`results/pydantic/plan.json\`)."
    echo
    python3 scripts/report.py --col "Codestral h0.7.0=$pc" --difficulty-json results/swe/difficulty.json
  fi
} > results/REPORT.md
echo "wrote results/REPORT.md with ${#cols[@]} args"
